### ISSUE TITLE
No error notification when wrong Topic name given

### ISSUE THREAD

**Issue by amit12cool** [pushtechnology/diffusion-examples#3]
Im using diffusion sdk 5.9.0 and able to connect and subscribe to topic is correct connection props and topic name are given.
Now, if i give incorrect topic name to session.subscribe function I don't get any error event on my session. Can you help how can i get the error event in above case?

**Comment by mattunderscorechampion** [comment]
You can't really subscribe to an incorrect topic name.
If you subscribe to a topic that doesn't exist, the subscription is treated as pending the creation of the topic. If the topic is created later, the session will be subscribed to it.
The backend can be [notified of subscriptions to missing topics](https://docs.pushtechnology.com/docs/6.3.2/manual/html/developerguide/client/topics/topiccontrol/missing_topic_notify.html) but it's only possible to be notified about all sessions not individual ones.
When subscribing it is possible to use [selectors](https://docs.pushtechnology.com/docs/6.3.2/manual/html/designguide/data/publication/topic_selector_unified.html) that select multiple topics not just one.
If the topic exists, then the stream should receive a notification that you have been subscribed to it. If it doesn't exist the notification won't happen.

**Comment by amit12cool** [comment]
So there is no way to show the caller that he has given a wrong topic name?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by mattunderscorechampion** [comment]
In more recent versions of the JS SDK or other language SDKs you can use something like the following to get close to what you want.

It's important to remember subscribing expresses interest in the paths described by the selector. That interest isn't affected by whether or not topics exist at those paths. If a session subscribes to a path without a topic, the session will receive notifications if a topic is ever created at that path.

```javascript
/**
 * Attempt to subscribe to a topic and report an error if the topic does not
 * exist.
 *
 * Returns a promise.
 */
function subscribe_to_topic(session, path, datatype) {
  return new Promise((resolve, reject) => {
    var success = false;
    // Add a stream to receive the topic notification
    let stream = session.addStream('>' + path, datatype);
    stream.on({
        subscribe : function (path, specification) {
          // Record that a subscription notification is received
          success = true;
        }
    });

    // Subscribe to the path
    session.select('>' + path).then(() => {
      // If the topic existed, the stream would have received an event before
      // this callback is called
      if (success) {
        // The session has been subscribed to a topic that exists
        resolve();
      } else {
        // The topic did not exist at the time of subscription or
        // the session doesn't have permission to subscribe to it.
        // Unsubscribe from the path and reject the promise.
        // Streams may receive events for this path if the topic is
        // created between the subscription and unsubscription.
        session.unsubscribe('>' + path);
        reject(new Error('Topic does not exist'));
      }

      // Clean up stream
      stream.close();
    }, (e) => {
      // The subscription failed so reject the promise and remove the stream
      stream.close();
      reject(e);
    });
  });
}
```
